### ISSUE TITLE
The Video isn't displayed

### ISSUE THREAD

**Issue by TEKNODEV2** [LunatiqueCoder/react-native-media-console#102]
I did everything necessary...but the player can't be seen....and the audio can still be heard

https://github.com/LunatiqueCoder/react-native-media-console/assets/86974717/b7c61073-3c16-435a-8dc8-85d78714c5b1

**Comment by Ahsanali012** [comment]
> I did everything necessary...but the player can't be seen....and the audio can still be heard
> 
>  Simulator.Screen.Recording.-.iPhone.12.mini.-.2024-02-12.at.11.30.43.mp4

Did you fixed or find other way ?

**Comment by LunatiqueCoder** [comment]
Be sure to use beta/alpha version of react-native-video. If you provide a reproduction code, that would be easier to look into.
