### ISSUE TITLE
UI controls have unexpected behavior compared with demo

### ISSUE THREAD

**Issue by coofzilla** [LunatiqueCoder/react-native-media-console#107]
In the demo the controls such as play/fwd, rwd seem to "depress" however, when using it, the play seems to scale very largely for a moment and play; while, the seek buttons dont have any visual indication that you've pressed the buttons.

https://github.com/LunatiqueCoder/react-native-media-console/assets/75731066/ad30b986-c6b9-4b9a-9df7-a27d10112f09

**Comment by LunatiqueCoder** [comment]
I can easily add some opacity feedback when the button is being pressed by using the `<Pressable />` API from `react-native`. I don't understand how/why the the play button scales largely, it's definitely not implemented by us, and also why the `<TouchableHighlight />` doesn't work like in the demo anymore. Anyway, will be looking into it :/

**Comment by coofzilla** [comment]
@LunatiqueCoder thank you, I appreciate you looking into this!

**Comment by coofzilla** [comment]
has there been any update to this? @LunatiqueCoder

**Comment by coofzilla** [comment]
@LunatiqueCoder thank you for the response! I appreciate it and totally understand.
