### ISSUE TITLE
Video continuously playing when we navigate to other screen

### ISSUE THREAD

**Issue by iamharisdev** [LunatiqueCoder/react-native-media-console#33]
`Video continuously playing when we navigate to other screen`

> this issue is on IOS

**Comment by criszz77** [comment]
Hello @Haris-teach 

Can you provide a reproducible example? Thank you!

**Comment by criszz77** [comment]
I just managed to reproduce this, but I think it's rather a [`react-nativei-video`](https://github.com/react-native-video/react-native-video) issue. Maybe this was fix in a current alpha version? You can try `yarn add react-native-video@next`

**Comment by shelcom** [comment]
You can try this for solved your problem: 

1) Add ref 
let videoPlayer = useRef<Video | null>(null);

2)Add useEffect
useEffect(() => {
    return () => {
      videoPlayer.current = null;
    };
  }, []);
  
3)Add ref to Player
<VideoPlayer
  videoRef={videoPlayer}
/>

**Comment by LunatiqueCoder** [comment]
Needs more info to reproduce. perhaps a reproduction repository?
