### ISSUE TITLE
Full Screen works only on Ios

### ISSUE THREAD

**Issue by tdammy92** [LunatiqueCoder/react-native-media-console#61]
This package doesnt support full screen on android. ?  😞

Please can you add full screen support for android.

**Comment by LunatiqueCoder** [comment]
Hello @tdammy92 

This package does not support full screen at all. It only offers you what you need to implement it based on your needs. Packages like [react-native-orientation-locker](https://github.com/wonday/react-native-orientation-locker) can come in handy, but that's really up to the user, and we dont want to force people to use OUR implementation of fullscreen, when they perhaps need something else.
