### ISSUE TITLE
showOnStart doesn't prevent controls to show when the video starts

### ISSUE THREAD

**Issue by fabiodc95neo** [LunatiqueCoder/react-native-media-console#78]
Hello, I'm trying to prevent the video player to show controls by default when video start but setting the prop showOnStart: false (default state by the way) isn't working and, also trying to disable each controls individually doesn't prevent the controls' animation effect (overlay effect) to show up. I'm currently reporting while working and testing with an android device (v13 installed).
Could anyone help me to solve this issue? Thanks in advance.

**Comment by LunatiqueCoder** [comment]
@fabiodc95neo Looking into it. For now, we're adding `disableOverlay` prop.

**Comment by LunatiqueCoder** [comment]
@fabiodc95neo For me it seems that `showOnStart={false}` works. Also, if I remove the prop also works. Closing for now until we have better reproduction steps or a reproduction repository.

**Comment by fabiodc95neo** [comment]
@LunatiqueCoder You're right, using the prop after a bunch of component's code changes seems to work well. Thank you for your support!
