### ISSUE TITLE
Maintainability status

### ISSUE THREAD

**Issue by saif-o99** [LunatiqueCoder/react-native-media-console#79]
Thank you for this great package.
i'm not trying to rush you, don't get me wrong but there are some open issues and pull requests preventing me from migrating to this package.
is there any specific time when these will be resolved?

**Comment by LunatiqueCoder** [comment]
Hello @saif-o99 

Some of them might be outdated. Can you paste here the links of the issues and PRs that interest you?

I believe starting from september I will be more active.

**Comment by saif-o99** [comment]
> I believe starting from september I will be more active.

Happy to hear that! .

these are some :
https://github.com/LunatiqueCoder/react-native-media-console/issues/26
https://github.com/LunatiqueCoder/react-native-media-console/issues/60
https://github.com/LunatiqueCoder/react-native-media-console/issues/78

but generally, Please try to close the Issues and the PRs that aren't valid / no in the package scope. it makes the package look much maintanable seeing fewer issues. 👍🏻

**Comment by saif-o99** [comment]
I can help if you need any help

**Comment by LunatiqueCoder** [comment]
I'm back. Started to cleanup issues and pull requests.
