### ISSUE TITLE
Cannot read property 'CONTAIN' of undefined.

### ISSUE THREAD

**Issue by dSukanta** [LunatiqueCoder/react-native-media-console#99]
If I install the package and do whatever mentioned in the npm documents , then I got error  undefined Unable to resolve module @react-native-media-console/reanimated  and if I remove the line- import {useAnimations} from '@react-native-media-console/reanimated'; got error -TypeError: Cannot read property 'CONTAIN' of undefined. What could fix this issue , any idea?

**Comment by LunatiqueCoder** [comment]
@dSukanta 

From the docs:

<img width="700" alt="image" src="https://github.com/LunatiqueCoder/react-native-media-console/assets/55203625/c7ec1d49-fb4b-4b6d-b410-74982c77ed69">

Try to use `react-native-video@6.0.0-beta.3`

You can also find the GitHub Docs here: https://github.com/LunatiqueCoder/react-native-media-console/tree/master/packages/media-console

**Comment by dSukanta** [comment]
@LunatiqueCoder is there anything extra installation guide for react-native-video@6.0.0-beta.3? Because , after installation , when I reran the app , I'm getting build error - > Task :app:checkDebugDuplicateClasses FAILED

**Comment by LunatiqueCoder** [comment]
@dSukanta 

I'm not sure but here are a few suggestions:

- Android only:  `cd android && ./gradlew clean && cd ..`
- iOS only: `cd ios && pod install && cd ..`
- Delete already installed apps before building/installing again
- Delete `node_modules`: `rm -rf node_modules`


What version of React Native are you using? Also, are you using Expo?

**Comment by LunatiqueCoder** [comment]
@dSukanta Here's a link to react-native-video installation docs, might be helpful: https://react-native-video.github.io/react-native-video/installation

Keep in mind they're a work in progress!

**Comment by LunatiqueCoder** [comment]
@dSukanta Also, be sure you don't have `@types/react-native-video` installed.
